### PR TITLE
Add additional codes for Leaseholder project and uplift DLO codes

### PR DESCRIPTION
**Pull request by pixeltrix**

### CODE REVIEW

**Comment by pixeltrix** [comment]
#843 will probably need merging before this one

**Review by LBHCallumM — APPROVED** [review]
I've had a skim through, but if there is a typo, I will most likely have missed it.

You should try running the migration against the database `repairs-db-db-local`. Its a clone of the dev database, and has the same connection string other than the name.

**Comment by pixeltrix** [comment]
> You should try running the migration against the database `repairs-db-db-local`. Its a clone of the dev database, and has the same connection string other than the name.

I dumped the schema from production and the contractors, contracts, sor_codes & sor_contracts tables - seems to run fine and I've tried to make the queries idempotent wherever possible.

**Review by Asura5 — APPROVED** [review]

**Comment by pixeltrix** [comment]
Updated with:
- additional Axis codes for drains, estate roads and paths enabled
- links inserted to the new contracts in the `property_contracts` table

**Pull request merged**
